import { db } from "./db";
import { candidateProfile, resumes, jobs, applicationAnswers, settings, contacts, resumeVersions } from "@shared/schema";
import { eq } from "drizzle-orm";

export async function seedDatabase() {
  const existingProfile = await db.select().from(candidateProfile).limit(1);
  if (existingProfile.length > 0) return;

  await db.insert(candidateProfile).values({
    fullName: "Alex Rivera",
    email: "alex.rivera@email.com",
    phone: "(312) 555-0198",
    location: "Chicago, IL",
    linkedinUrl: "https://linkedin.com/in/alexrivera",
    portfolioUrl: "https://alexrivera.dev",
    workAuthorization: "US Citizen",
    sponsorshipRequired: false,
    salaryPreference: "$80,000 - $110,000",
    willingToRelocate: true,
    preferredLocations: "Chicago, Remote, New York",
    preferredJobTypes: ["Remote", "Hybrid"],
    yearsOfExperience: "5",
  });

  const insertedResumes = await db.insert(resumes).values([
    {
      name: "Data Analyst Resume - General",
      roleType: "Data Analyst",
      plainText: "Alex Rivera | Data Analyst\nChicago, IL | alex.rivera@email.com\n\nSummary: Results-driven Data Analyst with 5 years of experience in SQL, Python, Tableau, and Excel. Strong background in data cleaning, statistical analysis, and reporting dashboards.\n\nExperience:\n- Senior Data Analyst, TechCorp (2021-Present): Built automated reporting pipelines, reduced report generation time by 40%. Created Tableau dashboards for executive team. Analyzed 5M+ records per month.\n- Data Analyst, DataWorks (2019-2021): Performed ad-hoc analysis, maintained ETL processes, supported business intelligence team.\n\nSkills: SQL, Python, Tableau, Power BI, Excel, R, ETL, Data Warehousing, Statistics, A/B Testing",
      active: true,
    },
    {
      name: "Healthcare Data Analyst Resume",
      roleType: "Healthcare Data Analyst",
      plainText: "Alex Rivera | Healthcare Data Analyst\nChicago, IL | alex.rivera@email.com\n\nSummary: Healthcare-focused Data Analyst with experience in clinical data, EHR systems, and regulatory reporting. HIPAA certified with strong SQL and analytics skills.\n\nExperience:\n- Senior Data Analyst, TechCorp (2021-Present): Analyzed healthcare claims data, built quality metrics dashboards, ensured HIPAA compliance in all data handling. Worked with 3M+ patient records.\n- Data Analyst, DataWorks (2019-2021): Supported clinical research team with data extraction and statistical analysis.\n\nSkills: SQL, Python, Tableau, Epic/EHR, HIPAA, Clinical Data, Healthcare Analytics, SAS, Power BI",
      active: true,
    },
    {
      name: "Healthcare Analyst Resume",
      roleType: "Healthcare Analyst",
      plainText: "Alex Rivera | Healthcare Analyst\nChicago, IL | alex.rivera@email.com\n\nSummary: Healthcare Analyst with expertise in operations analysis, quality improvement, and process optimization within healthcare organizations.\n\nExperience:\n- Senior Data Analyst, TechCorp (2021-Present): Led operational efficiency projects, analyzed patient flow data, presented findings to clinical leadership.\n- Data Analyst, DataWorks (2019-2021): Created operational reports, tracked KPIs for patient satisfaction and outcomes.\n\nSkills: Healthcare Operations, Process Improvement, SQL, Excel, Lean Six Sigma, Quality Metrics, Regulatory Compliance",
      active: true,
    },
    {
      name: "Business Analyst Resume",
      roleType: "Business Analyst",
      plainText: "Alex Rivera | Business Analyst\nChicago, IL | alex.rivera@email.com\n\nSummary: Business Analyst with strong requirements gathering, stakeholder management, and data analysis skills. Experienced in Agile environments.\n\nExperience:\n- Senior Data Analyst, TechCorp (2021-Present): Gathered business requirements, created process documentation, facilitated sprint planning sessions.\n- Data Analyst, DataWorks (2019-2021): Supported product team with market analysis and competitive research.\n\nSkills: Requirements Gathering, Agile/Scrum, JIRA, SQL, Stakeholder Management, Process Mapping, UAT, Business Intelligence",
      active: true,
    },
  ]).returning({ id: resumes.id });

  const resumeIds = insertedResumes.map(r => r.id);

  const insertedJobs = await db.insert(jobs).values([
    {
      title: "Data Analyst II",
      company: "Acme Analytics",
      source: "LinkedIn",
      location: "Chicago, IL",
      workMode: "Hybrid",
      datePosted: "2026-03-04",
      description: "We are looking for a Data Analyst to join our growing analytics team. You will work with SQL and Python to analyze large datasets, build Tableau dashboards, and present insights to stakeholders. Requirements: 3+ years of experience with SQL, Python, and data visualization tools. Experience with ETL processes preferred.",
      applyLink: "https://linkedin.com/jobs/12345",
      roleClassification: "Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 78,
      applyPriorityLabel: "High Priority",
      status: "Applied",
      priority: "High",
      dateApplied: "2026-03-05",
      atsScore: 82,
      atsScoreAtApply: 82,
      salaryMin: 85000,
      salaryMax: 105000,
      notes: "Great company culture, strong analytics team.",
      followUpDate: "2026-03-12",
      importSource: "__manual__",
    },
    {
      title: "Healthcare Data Analyst",
      company: "MedTech Solutions",
      source: "Indeed",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-03-03",
      description: "MedTech Solutions is seeking a Healthcare Data Analyst to support our clinical operations team. Responsibilities include analyzing clinical data, building reporting dashboards, and ensuring data quality across EHR systems. Must have experience with SQL, healthcare data standards, and HIPAA compliance.",
      applyLink: "https://indeed.com/jobs/67890",
      roleClassification: "Healthcare Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Healthcare Data Analyst",
      applyPriorityScore: 85,
      applyPriorityLabel: "Apply Immediately",
      status: "Interview",
      priority: "High",
      dateApplied: "2026-03-04",
      interviewDate: "2026-03-15",
      interviewRound: "Phone Screen",
      interviewResult: "Passed",
      atsScore: 88,
      atsScoreAtApply: 88,
      salaryMin: 90000,
      salaryMax: 115000,
      notes: "Passed phone screen. Round 2 scheduled with hiring manager.",
      followUpDate: "2026-03-15",
      recruiterName: "Jessica Lee",
      recruiterEmail: "j.lee@medtech.com",
      recruiterContactDate: "2026-03-06",
      importSource: "__manual__",
    },
    {
      title: "Business Analyst - Operations",
      company: "Global Dynamics",
      source: "Glassdoor",
      location: "New York, NY",
      workMode: "Onsite",
      datePosted: "2026-03-02",
      description: "Looking for a Business Analyst to drive operational improvements. You'll gather requirements from stakeholders, create process documentation, and work with the development team in an Agile environment. Experience with JIRA and SQL required.",
      applyLink: "https://glassdoor.com/jobs/abcde",
      roleClassification: "Business Analyst",
      fitLabel: "Possible Match",
      resumeRecommendation: "Business Analyst",
      applyPriorityScore: 61,
      applyPriorityLabel: "Medium Priority",
      status: "Applied",
      priority: "Medium",
      dateApplied: "2026-03-06",
      atsScore: 71,
      atsScoreAtApply: 71,
      salaryMin: 80000,
      salaryMax: 100000,
      notes: "Onsite in NYC. Would need to consider relocation or remote negotiation.",
      followUpDate: "2026-03-13",
      importSource: "__manual__",
    },
    {
      title: "Senior Data Analyst",
      company: "FinVista Corp",
      source: "LinkedIn",
      location: "San Francisco, CA",
      workMode: "Remote",
      datePosted: "2026-03-01",
      description: "FinVista is hiring a Senior Data Analyst for our finance analytics team. You will build data models, create automated reporting solutions, and mentor junior analysts. Requires 5+ years of experience with SQL, Python, and Tableau.",
      applyLink: "https://linkedin.com/jobs/senior-da",
      roleClassification: "Data Analyst",
      fitLabel: "Possible Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 68,
      applyPriorityLabel: "High Priority",
      status: "Applied",
      priority: "Medium",
      dateApplied: "2026-03-02",
      atsScore: 74,
      atsScoreAtApply: 74,
      salaryMin: 100000,
      salaryMax: 130000,
      notes: "Applied via LinkedIn Easy Apply. Waiting for response.",
      followUpDate: "2026-03-09",
      importSource: "__manual__",
    },
    {
      title: "Healthcare Analyst - Quality Improvement",
      company: "Northshore Health",
      source: "Company Website",
      location: "Chicago, IL",
      workMode: "Hybrid",
      datePosted: "2026-02-28",
      description: "Join our Quality Improvement team as a Healthcare Analyst. Responsibilities include tracking quality metrics, analyzing patient outcomes data, supporting regulatory compliance efforts, and presenting findings to clinical leadership. SQL and Excel skills required.",
      applyLink: "https://northshorehealth.com/careers/ha-qi",
      roleClassification: "Healthcare Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Healthcare Analyst",
      applyPriorityScore: 80,
      applyPriorityLabel: "Apply Immediately",
      status: "Final Round",
      priority: "High",
      dateApplied: "2026-02-28",
      interviewDate: "2026-03-10",
      interviewRound: "Final Round",
      interviewResult: "Pending",
      atsScore: 83,
      atsScoreAtApply: 83,
      salaryMin: 75000,
      salaryMax: 95000,
      notes: "Final round interview scheduled. Panel interview with 3 stakeholders.",
      followUpDate: "2026-03-20",
      recruiterName: "Mark Thompson",
      recruiterEmail: "m.thompson@northshorehealth.com",
      recruiterContactDate: "2026-03-01",
      importSource: "__manual__",
    },
    {
      title: "Data Analyst - Analytics Engineering",
      company: "StreamCorp",
      source: "Referral",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-02-20",
      description: "StreamCorp is looking for a Data Analyst with strong SQL and dbt skills to join our analytics engineering team. You will build and maintain data models, create dashboards, and partner with product teams.",
      applyLink: "https://streamcorp.com/careers/da-ae",
      roleClassification: "Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 88,
      applyPriorityLabel: "Apply Immediately",
      status: "Offer",
      priority: "High",
      dateApplied: "2026-02-21",
      interviewDate: "2026-03-01",
      interviewRound: "Final Round",
      interviewResult: "Offer Received",
      offerSalary: "105000",
      offerDate: "2026-03-08",
      offerDeadline: "2026-03-25",
      offerDecision: "Negotiating",
      offerNotes: "Base: $105k + 10% bonus + equity. Negotiating for $115k.",
      atsScore: 91,
      atsScoreAtApply: 91,
      salaryMin: 95000,
      salaryMax: 120000,
      notes: "Referred by John Chen. Received offer. Negotiating salary.",
      decisionDate: "2026-03-25",
      recruiterName: "Sarah Park",
      recruiterEmail: "s.park@streamcorp.com",
      recruiterContactDate: "2026-02-22",
      importSource: "__manual__",
    },
    {
      title: "Junior Data Analyst",
      company: "StartupXYZ",
      source: "Referral",
      location: "Austin, TX",
      workMode: "Remote",
      datePosted: "2026-02-25",
      description: "Entry-level Data Analyst position. Looking for someone with SQL knowledge and Excel skills. Will work on basic reporting and data entry. No experience required.",
      applyLink: "https://startupxyz.com/careers",
      roleClassification: "Data Analyst",
      fitLabel: "Weak Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 32,
      applyPriorityLabel: "Low Priority",
      status: "Skipped",
      priority: "Low",
      notes: "Too junior for current experience level.",
      followUpDate: "",
      importSource: "__manual__",
    },
    {
      title: "BI Analyst - Healthcare",
      company: "Optum Analytics",
      source: "LinkedIn",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-03-10",
      description: "Join Optum's healthcare analytics division as a BI Analyst. Build Power BI dashboards, analyze claims data, and support population health initiatives. Requires SQL, Power BI, and healthcare domain knowledge.",
      applyLink: "https://linkedin.com/jobs/optum-bi",
      roleClassification: "Healthcare Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Healthcare Data Analyst",
      applyPriorityScore: 84,
      applyPriorityLabel: "Apply Immediately",
      status: "Applied",
      priority: "High",
      dateApplied: "2026-03-11",
      atsScore: 86,
      atsScoreAtApply: 86,
      salaryMin: 88000,
      salaryMax: 110000,
      notes: "Strong match on healthcare + BI. Applied with tailored resume.",
      importSource: "__manual__",
    },
    {
      title: "Data Analyst",
      company: "RetailMetrics",
      source: "Indeed",
      location: "Chicago, IL",
      workMode: "Hybrid",
      datePosted: "2026-03-08",
      description: "RetailMetrics is hiring a Data Analyst to support our merchandising and supply chain teams. You will analyze sales data, build KPI dashboards, and present findings weekly. SQL and Tableau required.",
      applyLink: "https://indeed.com/jobs/retailmetrics-da",
      roleClassification: "Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 72,
      applyPriorityLabel: "High Priority",
      status: "Rejected",
      priority: "Medium",
      dateApplied: "2026-03-09",
      atsScore: 75,
      atsScoreAtApply: 75,
      salaryMin: 72000,
      salaryMax: 90000,
      notes: "Received rejection email 5 days after applying. No feedback.",
      importSource: "__manual__",
    },
    {
      title: "Analytics Engineer",
      company: "DataLayer",
      source: "LinkedIn",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-03-12",
      description: "DataLayer is seeking an Analytics Engineer with strong dbt, SQL, and Python skills. You will build scalable data models, maintain our data warehouse, and enable self-serve analytics across the organization.",
      applyLink: "https://linkedin.com/jobs/datalayer-ae",
      roleClassification: "Data Analyst",
      fitLabel: "Possible Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 66,
      applyPriorityLabel: "Medium Priority",
      status: "New",
      priority: "Medium",
      salaryMin: 95000,
      salaryMax: 125000,
      notes: "",
      importSource: "__manual__",
    },
    {
      title: "Healthcare Data Analyst III",
      company: "BlueCross Analytics",
      source: "Company Website",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-03-13",
      description: "BlueCross Analytics team is looking for a Healthcare Data Analyst III to support our member analytics function. You will analyze member utilization, build dashboards in Tableau, and support actuarial reporting. HIPAA and claims data experience required.",
      applyLink: "https://bcbs.com/careers/hda3",
      roleClassification: "Healthcare Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Healthcare Data Analyst",
      applyPriorityScore: 89,
      applyPriorityLabel: "Apply Immediately",
      status: "Reviewed",
      priority: "High",
      salaryMin: 92000,
      salaryMax: 118000,
      notes: "Top match — healthcare + claims experience. Need to apply ASAP.",
      importSource: "__manual__",
    },
  ]).returning({ id: jobs.id });

  const jobIds = insertedJobs.map(j => j.id);

  await db.insert(resumeVersions).values([
    {
      jobId: jobIds[1],
      resumeId: resumeIds[1],
      versionLabel: "v1 - MedTech Healthcare DA",
      company: "MedTech Solutions",
      jobTitle: "Healthcare Data Analyst",
      candidateName: "Alex Rivera",
      contact: "Chicago, IL | alex.rivera@email.com | (312) 555-0198",
      summary: "Healthcare Data Analyst with 5 years of experience in clinical data analysis, HIPAA-compliant reporting, and EHR systems. Expert in SQL, Power BI, and Tableau with proven track record in healthcare operations analytics.",
      skills: "SQL (Advanced), Python, Power BI, Tableau, Epic/EHR, HIPAA Compliance, Clinical Data Analysis, Healthcare Analytics, ETL, Data Warehousing",
      experience: "Senior Data Analyst, TechCorp (2021-Present): Analyzed 3M+ healthcare claims records monthly. Built 8+ Power BI dashboards for clinical KPIs. Ensured HIPAA compliance across all reporting workflows.\n\nData Analyst, DataWorks (2019-2021): Supported clinical research team with statistical analysis and EHR data extraction.",
      projects: "Healthcare Claims Dashboard: Built end-to-end Power BI dashboard tracking PMPM, medication adherence, and claims cycle time for 500K+ members.",
      education: "M.S. Business Analytics - Northwestern University (2019)\nB.S. Statistics - University of Illinois (2017)",
      certifications: "Microsoft Certified: Power BI Data Analyst (PL-300)\nHIPAA Certified Professional",
      atsScoreBefore: 71,
      atsScoreAfter: 88,
    },
    {
      jobId: jobIds[4],
      resumeId: resumeIds[2],
      versionLabel: "v1 - Northshore Healthcare Analyst",
      company: "Northshore Health",
      jobTitle: "Healthcare Analyst - Quality Improvement",
      candidateName: "Alex Rivera",
      contact: "Chicago, IL | alex.rivera@email.com | (312) 555-0198",
      summary: "Healthcare Analyst with expertise in quality improvement, patient outcomes analysis, and regulatory compliance. 5 years of experience partnering with clinical leadership to drive data-informed decisions.",
      skills: "SQL, Excel (Advanced), Power BI, Quality Metrics, Lean Six Sigma, Regulatory Reporting, Process Improvement, HIPAA, Patient Outcomes Analysis",
      experience: "Senior Data Analyst, TechCorp (2021-Present): Led quality improvement analytics for 3 hospital networks. Analyzed patient flow data and presented findings to C-suite. Reduced reporting turnaround by 35%.\n\nData Analyst, DataWorks (2019-2021): Created operational KPI reports and tracked patient satisfaction metrics.",
      projects: "Quality Metrics Dashboard: Built Excel + Power BI dashboard tracking 15+ quality KPIs including readmission rates, patient satisfaction, and compliance metrics.",
      education: "M.S. Business Analytics - Northwestern University (2019)\nB.S. Statistics - University of Illinois (2017)",
      certifications: "Lean Six Sigma Green Belt\nSQL for Data Analysis (Udemy)",
      atsScoreBefore: 68,
      atsScoreAfter: 83,
    },
    {
      jobId: jobIds[0],
      resumeId: resumeIds[0],
      versionLabel: "v1 - Acme Analytics Data Analyst",
      company: "Acme Analytics",
      jobTitle: "Data Analyst II",
      candidateName: "Alex Rivera",
      contact: "Chicago, IL | alex.rivera@email.com | (312) 555-0198",
      summary: "Data Analyst with 5 years of experience in SQL, Python, Tableau, and ETL pipeline development. Proven ability to transform complex datasets into actionable insights for executive stakeholders.",
      skills: "SQL (Advanced: CTEs, Window Functions, Query Optimization), Python (Pandas, NumPy, Scikit-learn), Tableau, Power BI, Excel, ETL, A/B Testing, Statistical Analysis",
      experience: "Senior Data Analyst, TechCorp (2021-Present): Built automated reporting pipelines reducing report generation time by 40%. Created Tableau dashboards used by 50+ executives. Analyzed 5M+ records monthly.\n\nData Analyst, DataWorks (2019-2021): Performed ad-hoc analysis, maintained ETL processes, supported BI team with dashboard maintenance.",
      projects: "Sales Performance Dashboard: Examined $25M revenue data across 8 regions using SQL and Tableau, identifying growth opportunities and reducing ad-hoc requests by 45%.",
      education: "M.S. Business Analytics - Northwestern University (2019)\nB.S. Statistics - University of Illinois (2017)",
      certifications: "Tableau Desktop Certified Associate\nSQL for Data Analysis (Udemy)\nPython for Data Science (Coursera)",
      atsScoreBefore: 74,
      atsScoreAfter: 82,
    },
  ]);

  await db.insert(contacts).values([
    {
      name: "Jessica Lee",
      title: "Technical Recruiter",
      company: "MedTech Solutions",
      email: "j.lee@medtech.com",
      phone: "(312) 555-0112",
      linkedinUrl: "https://linkedin.com/in/jessicalee-recruiter",
      contactType: "Recruiter",
      jobId: jobIds[1],
      lastContactDate: "2026-03-06",
      followUpDate: "2026-03-20",
      notes: "Very responsive. Scheduled phone screen quickly. Following up after final round.",
      isReferral: false,
    },
    {
      name: "John Chen",
      title: "Senior Data Analyst",
      company: "StreamCorp",
      email: "j.chen@streamcorp.com",
      linkedinUrl: "https://linkedin.com/in/johnchen-data",
      contactType: "Referral",
      jobId: jobIds[5],
      lastContactDate: "2026-02-18",
      followUpDate: "",
      notes: "Referred me for the Analytics Engineer role. Great inside contact — helped me tailor my resume.",
      isReferral: true,
    },
    {
      name: "Mark Thompson",
      title: "Director of Quality Improvement",
      company: "Northshore Health",
      email: "m.thompson@northshorehealth.com",
      contactType: "Hiring Manager",
      jobId: jobIds[4],
      lastContactDate: "2026-03-10",
      followUpDate: "2026-03-22",
      notes: "Conducted final round interview. Very interested in my healthcare background. Awaiting decision.",
      isReferral: false,
    },
    {
      name: "Priya Nair",
      title: "Data Science Lead",
      company: "Acme Analytics",
      email: "p.nair@acme.com",
      linkedinUrl: "https://linkedin.com/in/priyanair",
      contactType: "Connection",
      lastContactDate: "2026-03-01",
      followUpDate: "2026-03-28",
      notes: "Met at Chicago Data meetup. Connected on LinkedIn. Potential for future opportunities at Acme.",
      isReferral: false,
    },
    {
      name: "Sarah Park",
      title: "Talent Acquisition",
      company: "StreamCorp",
      email: "s.park@streamcorp.com",
      contactType: "Recruiter",
      jobId: jobIds[5],
      lastContactDate: "2026-03-08",
      followUpDate: "2026-03-24",
      notes: "Extended the offer. Negotiating for $115k. Very professional and transparent about comp structure.",
      isReferral: false,
    },
  ]);

  await db.insert(applicationAnswers).values([
    {
      question: "Why are you interested in this role?",
      answer: "I am passionate about using data to drive meaningful business decisions. With my background in SQL, Python, and data visualization, I am confident I can contribute to your team's analytical capabilities and help uncover insights that improve operations.",
    },
    {
      question: "Describe your experience with SQL",
      answer: "I have 5 years of hands-on SQL experience including complex queries, stored procedures, CTEs, window functions, and query optimization. I've worked with PostgreSQL, MySQL, and SQL Server across various projects involving millions of records.",
    },
    {
      question: "What is your greatest strength?",
      answer: "My greatest strength is translating complex data findings into clear, actionable recommendations for non-technical stakeholders. I focus on creating visual stories through dashboards that drive decision-making.",
    },
    {
      question: "Are you willing to work in a hybrid environment?",
      answer: "Yes, I am comfortable working in hybrid environments. I value both in-person collaboration and focused remote work, and I have experience being productive in both settings.",
    },
    {
      question: "What is your expected salary?",
      answer: "Based on my 5 years of experience and market research, I am targeting a base salary in the $85,000–$110,000 range, depending on the total compensation package including benefits, equity, and growth opportunities.",
    },
  ]);

  await db.insert(settings).values({
    key: "app_settings",
    value: {
      roleCategories: ["Data Analyst", "Healthcare Data Analyst", "Healthcare Analyst", "Business Analyst"],
      sources: ["LinkedIn", "Indeed", "Glassdoor", "Company Website", "Referral"],
      statuses: ["New", "Reviewed", "Ready to Apply", "Applied", "Skipped", "Interview", "Final Round", "Rejected", "Offer"],
    },
  });

  console.log("Seed data inserted successfully");
}
