import { db } from "./db";
import { candidateProfile, resumes, jobs, applicationAnswers, settings, contacts, resumeVersions } from "@shared/schema";
import { eq } from "drizzle-orm";

export async function seedDatabase() {
  const existingProfile = await db.select().from(candidateProfile).limit(1);
  if (existingProfile.length > 0) return;

  // ── Candidate Profile ─────────────────────────────────────────────────────
  await db.insert(candidateProfile).values({
    fullName: "Alex Rivera",
    email: "alex.rivera@email.com",
    phone: "(312) 555-0198",
    location: "Chicago, IL",
    linkedinUrl: "https://linkedin.com/in/alexrivera",
    portfolioUrl: "https://alexrivera.dev",
    workAuthorization: "US Citizen",
    sponsorshipRequired: false,
    salaryPreference: "$90,000 - $120,000",
    willingToRelocate: true,
    preferredLocations: "Chicago, Remote, New York",
    preferredJobTypes: ["Remote", "Hybrid"],
    yearsOfExperience: "5",
  });

  // ── Resumes ───────────────────────────────────────────────────────────────
  const insertedResumes = await db.insert(resumes).values([
    {
      name: "Data Analyst Resume - General",
      roleType: "Data Analyst",
      plainText: "Alex Rivera | Data Analyst\nChicago, IL | alex.rivera@email.com | (312) 555-0198\n\nSummary: Results-driven Data Analyst with 5 years of experience in SQL, Python, Tableau, and Excel. Strong background in data cleaning, statistical analysis, and reporting dashboards.\n\nExperience:\n- Senior Data Analyst, TechCorp (2021-Present): Built automated reporting pipelines, reduced report generation time by 40%. Created Tableau dashboards for executive team. Analyzed 5M+ records per month.\n- Data Analyst, DataWorks (2019-2021): Performed ad-hoc analysis, maintained ETL processes, supported business intelligence team.\n\nSkills: SQL, Python, Tableau, Power BI, Excel, R, ETL, Data Warehousing, Statistics, A/B Testing",
      active: true,
    },
    {
      name: "Healthcare Data Analyst Resume",
      roleType: "Healthcare Data Analyst",
      plainText: "Alex Rivera | Healthcare Data Analyst\nChicago, IL | alex.rivera@email.com | (312) 555-0198\n\nSummary: Healthcare-focused Data Analyst with experience in clinical data, EHR systems, and regulatory reporting. HIPAA certified with strong SQL and analytics skills.\n\nExperience:\n- Senior Data Analyst, TechCorp (2021-Present): Analyzed healthcare claims data, built quality metrics dashboards, ensured HIPAA compliance in all data handling. Worked with 3M+ patient records.\n- Data Analyst, DataWorks (2019-2021): Supported clinical research team with data extraction and statistical analysis.\n\nSkills: SQL, Python, Tableau, Epic/EHR, HIPAA, Clinical Data, Healthcare Analytics, SAS, Power BI",
      active: true,
    },
    {
      name: "Healthcare Analyst Resume",
      roleType: "Healthcare Analyst",
      plainText: "Alex Rivera | Healthcare Analyst\nChicago, IL | alex.rivera@email.com | (312) 555-0198\n\nSummary: Healthcare Analyst with expertise in operations analysis, quality improvement, and process optimization within healthcare organizations.\n\nExperience:\n- Senior Data Analyst, TechCorp (2021-Present): Led operational efficiency projects, analyzed patient flow data, presented findings to clinical leadership.\n- Data Analyst, DataWorks (2019-2021): Created operational reports, tracked KPIs for patient satisfaction and outcomes.\n\nSkills: Healthcare Operations, Process Improvement, SQL, Excel, Lean Six Sigma, Quality Metrics, Regulatory Compliance",
      active: true,
    },
    {
      name: "Business Analyst Resume",
      roleType: "Business Analyst",
      plainText: "Alex Rivera | Business Analyst\nChicago, IL | alex.rivera@email.com | (312) 555-0198\n\nSummary: Business Analyst with strong requirements gathering, stakeholder management, and data analysis skills. Experienced in Agile environments.\n\nExperience:\n- Senior Data Analyst, TechCorp (2021-Present): Gathered business requirements, created process documentation, facilitated sprint planning sessions.\n- Data Analyst, DataWorks (2019-2021): Supported product team with market analysis and competitive research.\n\nSkills: Requirements Gathering, Agile/Scrum, JIRA, SQL, Stakeholder Management, Process Mapping, UAT, Business Intelligence",
      active: true,
    },
  ]).returning({ id: resumes.id });

  const resumeIds = insertedResumes.map(r => r.id);

  // ── Jobs (20 total) ───────────────────────────────────────────────────────
  const insertedJobs = await db.insert(jobs).values([
    // ── 1: Applied — LinkedIn — Hybrid
    {
      title: "Data Analyst II",
      company: "Acme Analytics",
      source: "LinkedIn",
      location: "Chicago, IL",
      workMode: "Hybrid",
      datePosted: "2026-03-04",
      description: "We are looking for a Data Analyst to join our growing analytics team. You will work with SQL and Python to analyze large datasets, build Tableau dashboards, and present insights to stakeholders. Requirements: 3+ years of experience with SQL, Python, and data visualization tools. Experience with ETL processes preferred.",
      applyLink: "https://linkedin.com/jobs/12345",
      roleClassification: "Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 78,
      applyPriorityLabel: "High Priority",
      status: "Applied",
      priority: "High",
      dateApplied: "2026-03-05",
      atsScore: 82,
      atsScoreAtApply: 82,
      salaryMin: 85000,
      salaryMax: 105000,
      notes: "Great company culture, strong analytics team. Applied with tailored resume.",
      followUpDate: "2026-04-01",
      resumeVersionId: null,
      importSource: "__manual__",
    },
    // ── 2: Interview — Indeed — Remote
    {
      title: "Healthcare Data Analyst",
      company: "MedTech Solutions",
      source: "Indeed",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-03-03",
      description: "MedTech Solutions is seeking a Healthcare Data Analyst to support our clinical operations team. Responsibilities include analyzing clinical data, building reporting dashboards, and ensuring data quality across EHR systems. Must have experience with SQL, healthcare data standards, and HIPAA compliance.",
      applyLink: "https://indeed.com/jobs/67890",
      roleClassification: "Healthcare Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Healthcare Data Analyst",
      applyPriorityScore: 85,
      applyPriorityLabel: "Apply Immediately",
      status: "Interview",
      priority: "High",
      dateApplied: "2026-03-04",
      interviewDate: "2026-03-15",
      interviewRound: "Phone Screen",
      interviewResult: "Passed",
      atsScore: 88,
      atsScoreAtApply: 88,
      salaryMin: 90000,
      salaryMax: 115000,
      notes: "Passed phone screen. Round 2 scheduled with hiring manager on March 22.",
      followUpDate: "2026-03-22",
      recruiterName: "Jessica Lee",
      recruiterEmail: "j.lee@medtech.com",
      recruiterContactDate: "2026-03-06",
      importSource: "__manual__",
    },
    // ── 3: Applied — Glassdoor — Onsite
    {
      title: "Business Analyst - Operations",
      company: "Global Dynamics",
      source: "Glassdoor",
      location: "New York, NY",
      workMode: "Onsite",
      datePosted: "2026-03-02",
      description: "Looking for a Business Analyst to drive operational improvements. You'll gather requirements from stakeholders, create process documentation, and work with the development team in an Agile environment. Experience with JIRA and SQL required. Healthcare industry experience a plus.",
      applyLink: "https://glassdoor.com/jobs/abcde",
      roleClassification: "Business Analyst",
      fitLabel: "Possible Match",
      resumeRecommendation: "Business Analyst",
      applyPriorityScore: 61,
      applyPriorityLabel: "Medium Priority",
      status: "Applied",
      priority: "Medium",
      dateApplied: "2026-03-06",
      atsScore: 71,
      atsScoreAtApply: 71,
      salaryMin: 80000,
      salaryMax: 100000,
      notes: "Onsite in NYC. Would need to consider relocation or remote negotiation.",
      followUpDate: "2026-04-01",
      importSource: "__manual__",
    },
    // ── 4: Applied — LinkedIn — Remote
    {
      title: "Senior Data Analyst",
      company: "FinVista Corp",
      source: "LinkedIn",
      location: "San Francisco, CA",
      workMode: "Remote",
      datePosted: "2026-03-01",
      description: "FinVista is hiring a Senior Data Analyst for our finance analytics team. You will build data models, create automated reporting solutions, and mentor junior analysts. Requires 5+ years of experience with SQL, Python, and Tableau. Financial services experience preferred.",
      applyLink: "https://linkedin.com/jobs/senior-da",
      roleClassification: "Data Analyst",
      fitLabel: "Possible Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 68,
      applyPriorityLabel: "High Priority",
      status: "Applied",
      priority: "Medium",
      dateApplied: "2026-03-02",
      atsScore: 74,
      atsScoreAtApply: 74,
      salaryMin: 100000,
      salaryMax: 130000,
      notes: "Applied via LinkedIn Easy Apply. Waiting for response.",
      followUpDate: "2026-04-01",
      importSource: "__manual__",
    },
    // ── 5: Final Round — Company Website — Hybrid
    {
      title: "Healthcare Analyst - Quality Improvement",
      company: "Northshore Health",
      source: "Company Website",
      location: "Chicago, IL",
      workMode: "Hybrid",
      datePosted: "2026-02-28",
      description: "Join our Quality Improvement team as a Healthcare Analyst. Responsibilities include tracking quality metrics, analyzing patient outcomes data, supporting regulatory compliance efforts, and presenting findings to clinical leadership. SQL and Excel skills required.",
      applyLink: "https://northshorehealth.com/careers/ha-qi",
      roleClassification: "Healthcare Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Healthcare Analyst",
      applyPriorityScore: 80,
      applyPriorityLabel: "Apply Immediately",
      status: "Final Round",
      priority: "High",
      dateApplied: "2026-02-28",
      interviewDate: "2026-03-10",
      interviewRound: "Final Round",
      interviewResult: "Pending",
      atsScore: 83,
      atsScoreAtApply: 83,
      salaryMin: 75000,
      salaryMax: 95000,
      notes: "Final round panel interview with 3 stakeholders. Very positive feedback.",
      followUpDate: "2026-03-25",
      recruiterName: "Mark Thompson",
      recruiterEmail: "m.thompson@northshorehealth.com",
      recruiterContactDate: "2026-03-01",
      importSource: "__manual__",
    },
    // ── 6: Offer — Referral — Remote (THE OFFER)
    {
      title: "Data Analyst - Analytics Engineering",
      company: "StreamCorp",
      source: "Referral",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-02-20",
      description: "StreamCorp is looking for a Data Analyst with strong SQL and dbt skills to join our analytics engineering team. You will build and maintain data models, create dashboards, and partner with product teams.",
      applyLink: "https://streamcorp.com/careers/da-ae",
      roleClassification: "Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 88,
      applyPriorityLabel: "Apply Immediately",
      status: "Offer",
      priority: "High",
      dateApplied: "2026-02-21",
      interviewDate: "2026-03-01",
      interviewRound: "Final Round",
      interviewResult: "Offer Received",
      offerSalary: "105000",
      offerDate: "2026-03-08",
      offerDeadline: "2026-04-05",
      offerDecision: "Negotiating",
      offerNotes: "Base: $105k + 10% bonus + equity. Negotiating for $115k. Very excited about this role.",
      atsScore: 91,
      atsScoreAtApply: 91,
      salaryMin: 95000,
      salaryMax: 120000,
      notes: "Referred by John Chen. Received offer on March 8. Negotiating salary to $115k.",
      decisionDate: "2026-04-05",
      recruiterName: "Sarah Park",
      recruiterEmail: "s.park@streamcorp.com",
      recruiterContactDate: "2026-02-22",
      importSource: "__manual__",
    },
    // ── 7: Skipped — Referral — Remote
    {
      title: "Junior Data Analyst",
      company: "StartupXYZ",
      source: "Referral",
      location: "Austin, TX",
      workMode: "Remote",
      datePosted: "2026-02-25",
      description: "Entry-level Data Analyst position. Looking for someone with SQL knowledge and Excel skills. Will work on basic reporting and data entry. No experience required.",
      applyLink: "https://startupxyz.com/careers",
      roleClassification: "Data Analyst",
      fitLabel: "Weak Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 32,
      applyPriorityLabel: "Low Priority",
      status: "Skipped",
      priority: "Low",
      notes: "Too junior for current experience level.",
      importSource: "__manual__",
    },
    // ── 8: Applied — LinkedIn — Remote
    {
      title: "BI Analyst - Healthcare",
      company: "Optum Analytics",
      source: "LinkedIn",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-03-10",
      description: "Join Optum's healthcare analytics division as a BI Analyst. Build Power BI dashboards, analyze claims data, and support population health initiatives. Requires SQL, Power BI, and healthcare domain knowledge.",
      applyLink: "https://linkedin.com/jobs/optum-bi",
      roleClassification: "Healthcare Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Healthcare Data Analyst",
      applyPriorityScore: 84,
      applyPriorityLabel: "Apply Immediately",
      status: "Applied",
      priority: "High",
      dateApplied: "2026-03-11",
      atsScore: 86,
      atsScoreAtApply: 86,
      salaryMin: 88000,
      salaryMax: 110000,
      notes: "Strong match on healthcare + BI. Applied with tailored resume.",
      importSource: "__manual__",
    },
    // ── 9: Rejected — Indeed — Hybrid
    {
      title: "Data Analyst",
      company: "RetailMetrics Inc",
      source: "Indeed",
      location: "Chicago, IL",
      workMode: "Hybrid",
      datePosted: "2026-03-08",
      description: "RetailMetrics is hiring a Data Analyst to support our merchandising and supply chain teams. You will analyze sales data, build KPI dashboards, and present findings weekly. SQL and Tableau required.",
      applyLink: "https://indeed.com/jobs/retailmetrics-da",
      roleClassification: "Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 72,
      applyPriorityLabel: "High Priority",
      status: "Rejected",
      priority: "Medium",
      dateApplied: "2026-03-09",
      atsScore: 75,
      atsScoreAtApply: 75,
      salaryMin: 72000,
      salaryMax: 90000,
      notes: "Received rejection email 5 days after applying. No feedback provided.",
      importSource: "__manual__",
    },
    // ── 10: New — LinkedIn — Remote
    {
      title: "Analytics Engineer",
      company: "DataLayer",
      source: "LinkedIn",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-03-12",
      description: "DataLayer is seeking an Analytics Engineer with strong dbt, SQL, and Python skills. You will build scalable data models, maintain our data warehouse, and enable self-serve analytics across the organization.",
      applyLink: "https://linkedin.com/jobs/datalayer-ae",
      roleClassification: "Data Analyst",
      fitLabel: "Possible Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 66,
      applyPriorityLabel: "Medium Priority",
      status: "New",
      priority: "Medium",
      salaryMin: 95000,
      salaryMax: 125000,
      notes: "",
      importSource: "__manual__",
    },
    // ── 11: Reviewed — Company Website — Remote
    {
      title: "Healthcare Data Analyst III",
      company: "BlueCross Analytics",
      source: "Company Website",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-03-13",
      description: "BlueCross Analytics team is looking for a Healthcare Data Analyst III to support our member analytics function. You will analyze member utilization, build dashboards in Tableau, and support actuarial reporting. HIPAA and claims data experience required.",
      applyLink: "https://bcbs.com/careers/hda3",
      roleClassification: "Healthcare Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Healthcare Data Analyst",
      applyPriorityScore: 89,
      applyPriorityLabel: "Apply Immediately",
      status: "Reviewed",
      priority: "High",
      salaryMin: 92000,
      salaryMax: 118000,
      notes: "Top match — healthcare + claims experience. Need to apply ASAP.",
      importSource: "__manual__",
    },
    // ── 12: Interview — Recruiter — Remote (2nd interview)
    {
      title: "Product Analyst",
      company: "TechNova",
      source: "Recruiter",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-03-05",
      description: "TechNova is looking for a Product Analyst to join our growth team. You'll analyze user behavior, run A/B tests, work with Mixpanel and BigQuery, and collaborate closely with product managers to drive data-informed decisions.",
      applyLink: "https://technova.io/jobs/product-analyst",
      roleClassification: "Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 81,
      applyPriorityLabel: "Apply Immediately",
      status: "Interview",
      priority: "High",
      dateApplied: "2026-03-07",
      interviewDate: "2026-03-18",
      interviewRound: "Round 1 Technical",
      interviewResult: "Passed",
      atsScore: 84,
      atsScoreAtApply: 84,
      salaryMin: 95000,
      salaryMax: 120000,
      notes: "Recruiter reached out on LinkedIn. Technical round passed. Waiting for round 2 details.",
      recruiterName: "Lisa Huang",
      recruiterEmail: "l.huang@technova.io",
      recruiterContactDate: "2026-03-05",
      importSource: "__manual__",
    },
    // ── 13: Applied — Indeed — Remote
    {
      title: "Data Analyst - Marketing",
      company: "BrandMetrics",
      source: "Indeed",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-03-09",
      description: "BrandMetrics is seeking a Data Analyst to support our marketing analytics function. You'll work with Google Analytics, Looker, and SQL to measure campaign performance, build attribution models, and deliver weekly reports to the CMO.",
      applyLink: "https://indeed.com/jobs/brandmetrics-da",
      roleClassification: "Data Analyst",
      fitLabel: "Possible Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 60,
      applyPriorityLabel: "Medium Priority",
      status: "Applied",
      priority: "Medium",
      dateApplied: "2026-03-10",
      atsScore: 69,
      atsScoreAtApply: 69,
      salaryMin: 75000,
      salaryMax: 95000,
      notes: "Applied with general resume. Marketing analytics is a slight stretch but worth trying.",
      importSource: "__manual__",
    },
    // ── 14: No Response — Glassdoor — Onsite
    {
      title: "Data Engineer I",
      company: "CorePipeline",
      source: "Glassdoor",
      location: "Boston, MA",
      workMode: "Onsite",
      datePosted: "2026-02-22",
      description: "CorePipeline is hiring a junior Data Engineer to build and maintain ETL pipelines. Requires Python, SQL, and Airflow experience. AWS or GCP preferred.",
      applyLink: "https://glassdoor.com/jobs/corepipeline",
      roleClassification: "Data Analyst",
      fitLabel: "Possible Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 48,
      applyPriorityLabel: "Low Priority",
      status: "No Response",
      priority: "Low",
      dateApplied: "2026-02-24",
      atsScore: 58,
      atsScoreAtApply: 58,
      salaryMin: 80000,
      salaryMax: 100000,
      notes: "Applied 3 weeks ago. No response. Job was onsite in Boston which is a reach.",
      importSource: "__manual__",
    },
    // ── 15: Interview — LinkedIn — Hybrid (3rd interview)
    {
      title: "Clinical Data Analyst",
      company: "Northwestern Medicine",
      source: "LinkedIn",
      location: "Chicago, IL",
      workMode: "Hybrid",
      datePosted: "2026-03-11",
      description: "Northwestern Medicine is seeking a Clinical Data Analyst to support our quality and outcomes reporting team. You'll work with Epic EMR data, SQL Server, and Power BI to support clinical leadership decision-making.",
      applyLink: "https://nm.org/careers/cda",
      roleClassification: "Healthcare Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Healthcare Data Analyst",
      applyPriorityScore: 87,
      applyPriorityLabel: "Apply Immediately",
      status: "Interview",
      priority: "High",
      dateApplied: "2026-03-12",
      interviewDate: "2026-03-20",
      interviewRound: "Phone Screen",
      interviewResult: "Pending",
      atsScore: 89,
      atsScoreAtApply: 89,
      salaryMin: 80000,
      salaryMax: 105000,
      notes: "Phone screen with HR scheduled for March 20. Very strong match on healthcare + Epic experience.",
      recruiterName: "Amy Walsh",
      recruiterEmail: "a.walsh@nm.org",
      recruiterContactDate: "2026-03-13",
      importSource: "__manual__",
    },
    // ── 16: Ready to Apply — Recruiter — Hybrid
    {
      title: "Operations Analyst",
      company: "Midwest Logistics",
      source: "Recruiter",
      location: "Chicago, IL",
      workMode: "Hybrid",
      datePosted: "2026-03-14",
      description: "Midwest Logistics is hiring an Operations Analyst to optimize freight and supply chain operations. Requires SQL, Excel, and experience with Tableau or Power BI. Logistics or operations background a plus.",
      applyLink: "https://midwestlogistics.com/jobs/ops-analyst",
      roleClassification: "Business Analyst",
      fitLabel: "Possible Match",
      resumeRecommendation: "Business Analyst",
      applyPriorityScore: 58,
      applyPriorityLabel: "Medium Priority",
      status: "Ready to Apply",
      priority: "Medium",
      salaryMin: 70000,
      salaryMax: 90000,
      notes: "Recruiter sent this over. Resume needs minor tailoring before applying.",
      importSource: "__manual__",
    },
    // ── 17: Applied — LinkedIn — Remote
    {
      title: "Insights Analyst",
      company: "Aperture Research",
      source: "LinkedIn",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-03-06",
      description: "Aperture Research seeks an Insights Analyst with strong statistical modeling and survey data experience. You'll work with R or Python, build dashboards, and present market research findings to Fortune 500 clients.",
      applyLink: "https://linkedin.com/jobs/aperture-ia",
      roleClassification: "Data Analyst",
      fitLabel: "Possible Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 62,
      applyPriorityLabel: "Medium Priority",
      status: "Applied",
      priority: "Medium",
      dateApplied: "2026-03-08",
      atsScore: 67,
      atsScoreAtApply: 67,
      salaryMin: 78000,
      salaryMax: 98000,
      notes: "Applied with general data analyst resume. Interesting work in market research.",
      importSource: "__manual__",
    },
    // ── 18: Rejected — Indeed — Onsite
    {
      title: "Financial Analyst - FP&A",
      company: "Summit Capital",
      source: "Indeed",
      location: "New York, NY",
      workMode: "Onsite",
      datePosted: "2026-02-26",
      description: "Summit Capital is hiring a Financial Analyst for our FP&A team. Requires advanced Excel, financial modeling, and SQL. CFA or MBA preferred. Will support budgeting, forecasting, and variance analysis.",
      applyLink: "https://summitcapital.com/careers",
      roleClassification: "Business Analyst",
      fitLabel: "Weak Match",
      resumeRecommendation: "Business Analyst",
      applyPriorityScore: 38,
      applyPriorityLabel: "Low Priority",
      status: "Rejected",
      priority: "Low",
      dateApplied: "2026-02-27",
      atsScore: 52,
      atsScoreAtApply: 52,
      salaryMin: 90000,
      salaryMax: 115000,
      notes: "Rejected within 48 hours. Role was more finance-specific than data analytics.",
      importSource: "__manual__",
    },
    // ── 19: Saved — Company Website — Remote
    {
      title: "People Analytics Analyst",
      company: "HRTech Global",
      source: "Company Website",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-03-15",
      description: "HRTech Global is looking for a People Analytics Analyst to build workforce analytics capabilities. You'll use SQL, Python, and Tableau to analyze employee engagement, retention, and performance data. HRIS experience preferred.",
      applyLink: "https://hrtech.io/careers/paa",
      roleClassification: "Data Analyst",
      fitLabel: "Possible Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 55,
      applyPriorityLabel: "Medium Priority",
      status: "Saved",
      priority: "Medium",
      salaryMin: 82000,
      salaryMax: 105000,
      notes: "Interesting niche. Saved for later review — want to research the company more.",
      importSource: "__manual__",
    },
    // ── 20: New — LinkedIn — Remote
    {
      title: "Data Analyst - Supply Chain",
      company: "GlobalOps Inc",
      source: "LinkedIn",
      location: "Remote",
      workMode: "Remote",
      datePosted: "2026-03-16",
      description: "GlobalOps is hiring a Data Analyst to support our supply chain operations team. You will analyze inventory data, build Tableau dashboards, and partner with procurement and logistics managers. SQL and Python required.",
      applyLink: "https://linkedin.com/jobs/globalops-scda",
      roleClassification: "Data Analyst",
      fitLabel: "Strong Match",
      resumeRecommendation: "Data Analyst",
      applyPriorityScore: 73,
      applyPriorityLabel: "High Priority",
      status: "New",
      priority: "High",
      salaryMin: 83000,
      salaryMax: 108000,
      notes: "",
      importSource: "__manual__",
    },
  ]).returning({ id: jobs.id });

  const jobIds = insertedJobs.map(j => j.id);

  // ── Resume Versions (4 versions) ─────────────────────────────────────────
  await db.insert(resumeVersions).values([
    {
      jobId: jobIds[1], // MedTech Healthcare DA
      resumeId: resumeIds[1],
      versionLabel: "v1 - MedTech Healthcare DA",
      company: "MedTech Solutions",
      jobTitle: "Healthcare Data Analyst",
      candidateName: "Alex Rivera",
      contact: "Chicago, IL | alex.rivera@email.com | (312) 555-0198",
      summary: "Healthcare Data Analyst with 5 years of experience in clinical data analysis, HIPAA-compliant reporting, and EHR systems. Expert in SQL, Power BI, and Tableau with proven track record in healthcare operations analytics.",
      skills: "SQL (Advanced), Python, Power BI, Tableau, Epic/EHR, HIPAA Compliance, Clinical Data Analysis, Healthcare Analytics, ETL, Data Warehousing",
      experience: "Senior Data Analyst, TechCorp (2021-Present): Analyzed 3M+ healthcare claims records monthly. Built 8+ Power BI dashboards for clinical KPIs. Ensured HIPAA compliance across all reporting workflows.\n\nData Analyst, DataWorks (2019-2021): Supported clinical research team with statistical analysis and EHR data extraction.",
      projects: "Healthcare Claims Dashboard: Built end-to-end Power BI dashboard tracking PMPM, medication adherence, and claims cycle time for 500K+ members.",
      education: "M.S. Business Analytics - Northwestern University (2019)\nB.S. Statistics - University of Illinois (2017)",
      certifications: "Microsoft Certified: Power BI Data Analyst (PL-300)\nHIPAA Certified Professional",
      atsScoreBefore: 71,
      atsScoreAfter: 88,
    },
    {
      jobId: jobIds[4], // Northshore Health Final Round
      resumeId: resumeIds[2],
      versionLabel: "v1 - Northshore Healthcare Analyst",
      company: "Northshore Health",
      jobTitle: "Healthcare Analyst - Quality Improvement",
      candidateName: "Alex Rivera",
      contact: "Chicago, IL | alex.rivera@email.com | (312) 555-0198",
      summary: "Healthcare Analyst with expertise in quality improvement, patient outcomes analysis, and regulatory compliance. 5 years of experience partnering with clinical leadership to drive data-informed decisions.",
      skills: "SQL, Excel (Advanced), Power BI, Quality Metrics, Lean Six Sigma, Regulatory Reporting, Process Improvement, HIPAA, Patient Outcomes Analysis",
      experience: "Senior Data Analyst, TechCorp (2021-Present): Led quality improvement analytics for 3 hospital networks. Analyzed patient flow data and presented findings to C-suite. Reduced reporting turnaround by 35%.\n\nData Analyst, DataWorks (2019-2021): Created operational KPI reports and tracked patient satisfaction metrics.",
      projects: "Quality Metrics Dashboard: Built Excel + Power BI dashboard tracking 15+ quality KPIs including readmission rates, patient satisfaction, and compliance metrics.",
      education: "M.S. Business Analytics - Northwestern University (2019)\nB.S. Statistics - University of Illinois (2017)",
      certifications: "Lean Six Sigma Green Belt\nSQL for Data Analysis (Udemy)",
      atsScoreBefore: 68,
      atsScoreAfter: 83,
    },
    {
      jobId: jobIds[0], // Acme Analytics Applied
      resumeId: resumeIds[0],
      versionLabel: "v1 - Acme Analytics Data Analyst",
      company: "Acme Analytics",
      jobTitle: "Data Analyst II",
      candidateName: "Alex Rivera",
      contact: "Chicago, IL | alex.rivera@email.com | (312) 555-0198",
      summary: "Data Analyst with 5 years of experience in SQL, Python, Tableau, and ETL pipeline development. Proven ability to transform complex datasets into actionable insights for executive stakeholders.",
      skills: "SQL (Advanced: CTEs, Window Functions, Query Optimization), Python (Pandas, NumPy, Scikit-learn), Tableau, Power BI, Excel, ETL, A/B Testing, Statistical Analysis",
      experience: "Senior Data Analyst, TechCorp (2021-Present): Built automated reporting pipelines reducing report generation time by 40%. Created Tableau dashboards used by 50+ executives. Analyzed 5M+ records monthly.\n\nData Analyst, DataWorks (2019-2021): Performed ad-hoc analysis, maintained ETL processes, supported BI team with dashboard maintenance.",
      projects: "Sales Performance Dashboard: Examined $25M revenue data across 8 regions using SQL and Tableau, identifying growth opportunities and reducing ad-hoc requests by 45%.",
      education: "M.S. Business Analytics - Northwestern University (2019)\nB.S. Statistics - University of Illinois (2017)",
      certifications: "Tableau Desktop Certified Associate\nSQL for Data Analysis (Udemy)\nPython for Data Science (Coursera)",
      atsScoreBefore: 74,
      atsScoreAfter: 82,
    },
    {
      jobId: jobIds[5], // StreamCorp Offer
      resumeId: resumeIds[0],
      versionLabel: "v1 - StreamCorp Analytics Engineer",
      company: "StreamCorp",
      jobTitle: "Data Analyst - Analytics Engineering",
      candidateName: "Alex Rivera",
      contact: "Chicago, IL | alex.rivera@email.com | (312) 555-0198",
      summary: "Data Analyst with strong dbt, SQL, and Python skills. Experienced in building scalable data models and enabling self-serve analytics. Passionate about analytics engineering and data reliability.",
      skills: "SQL (Advanced), Python, dbt, Tableau, Looker, ETL, Data Modeling, Airflow, BigQuery, Snowflake, Git, Analytics Engineering",
      experience: "Senior Data Analyst, TechCorp (2021-Present): Built dbt data models powering 20+ Tableau dashboards. Migrated legacy ETL to modern cloud stack. Reduced pipeline failures by 60%.\n\nData Analyst, DataWorks (2019-2021): Designed SQL-based reporting pipelines and maintained data warehouse documentation.",
      projects: "Modern Data Stack Migration: Led migration from legacy ETL to dbt + Snowflake + Tableau stack. Improved data freshness from daily to hourly for 15+ critical business metrics.",
      education: "M.S. Business Analytics - Northwestern University (2019)\nB.S. Statistics - University of Illinois (2017)",
      certifications: "dbt Analytics Engineering Certification\nSnowflake SnowPro Core\nTableau Desktop Certified Associate",
      atsScoreBefore: 79,
      atsScoreAfter: 91,
    },
  ]);

  // ── Contacts (5 contacts) ─────────────────────────────────────────────────
  await db.insert(contacts).values([
    {
      name: "Jessica Lee",
      title: "Technical Recruiter",
      company: "MedTech Solutions",
      email: "j.lee@medtech.com",
      phone: "(312) 555-0112",
      linkedinUrl: "https://linkedin.com/in/jessicalee-recruiter",
      contactType: "Recruiter",
      jobId: jobIds[1],
      lastContactDate: "2026-03-06",
      followUpDate: "2026-03-22",
      notes: "Very responsive. Scheduled phone screen quickly. Following up after final round.",
      isReferral: false,
    },
    {
      name: "John Chen",
      title: "Senior Data Analyst",
      company: "StreamCorp",
      email: "j.chen@streamcorp.com",
      linkedinUrl: "https://linkedin.com/in/johnchen-data",
      contactType: "Referral",
      jobId: jobIds[5],
      lastContactDate: "2026-02-18",
      followUpDate: "",
      notes: "Referred me for the Analytics Engineer role. Great inside contact — helped me tailor my resume to the job description.",
      isReferral: true,
    },
    {
      name: "Mark Thompson",
      title: "Director of Quality Improvement",
      company: "Northshore Health",
      email: "m.thompson@northshorehealth.com",
      contactType: "Hiring Manager",
      jobId: jobIds[4],
      lastContactDate: "2026-03-10",
      followUpDate: "2026-03-25",
      notes: "Conducted final round interview. Very interested in my healthcare background. Awaiting decision.",
      isReferral: false,
    },
    {
      name: "Priya Nair",
      title: "Data Science Lead",
      company: "Acme Analytics",
      email: "p.nair@acme.com",
      linkedinUrl: "https://linkedin.com/in/priyanair",
      contactType: "Connection",
      lastContactDate: "2026-03-01",
      followUpDate: "2026-04-01",
      notes: "Met at Chicago Data meetup. Connected on LinkedIn. Potential for future opportunities at Acme Analytics.",
      isReferral: false,
    },
    {
      name: "Sarah Park",
      title: "Talent Acquisition Manager",
      company: "StreamCorp",
      email: "s.park@streamcorp.com",
      phone: "(415) 555-0234",
      contactType: "Recruiter",
      jobId: jobIds[5],
      lastContactDate: "2026-03-08",
      followUpDate: "2026-04-01",
      notes: "Extended the offer. Negotiating for $115k. Very professional and transparent about comp structure.",
      isReferral: false,
    },
  ]);

  // ── Application Answers ───────────────────────────────────────────────────
  await db.insert(applicationAnswers).values([
    {
      question: "Why are you interested in this role?",
      answer: "I am passionate about using data to drive meaningful business decisions. With my background in SQL, Python, and data visualization, I am confident I can contribute to your team's analytical capabilities and help uncover insights that improve operations.",
    },
    {
      question: "Describe your experience with SQL",
      answer: "I have 5 years of hands-on SQL experience including complex queries, stored procedures, CTEs, window functions, and query optimization. I've worked with PostgreSQL, MySQL, and SQL Server across various projects involving millions of records.",
    },
    {
      question: "What is your greatest strength?",
      answer: "My greatest strength is translating complex data findings into clear, actionable recommendations for non-technical stakeholders. I focus on creating visual stories through dashboards that drive decision-making.",
    },
    {
      question: "Describe a challenging project you worked on",
      answer: "At TechCorp, I led a project to consolidate 12 disparate data sources into a single reporting warehouse. I designed the ETL pipelines in Python, wrote the SQL data models, and built Tableau dashboards that reduced executive reporting time by 40%.",
    },
    {
      question: "Where do you see yourself in 5 years?",
      answer: "I see myself growing into a senior analytics or analytics engineering role where I can mentor junior analysts, architect data infrastructure, and serve as a strategic partner to business leadership — using data to drive company-wide decisions.",
    },
  ]);

  // ── Default Settings ──────────────────────────────────────────────────────
  await db.insert(settings).values([
    {
      key: "app_settings",
      value: JSON.stringify({
        targetRoles: ["Data Analyst", "Healthcare Data Analyst", "Business Analyst", "Analytics Engineer"],
        preferredLocations: ["Remote", "Chicago, IL"],
        salaryMin: 80000,
        salaryMax: 130000,
        workModes: ["Remote", "Hybrid"],
        jobSources: ["LinkedIn", "Indeed", "Glassdoor", "Company Website", "Referral"],
        keywords: ["SQL", "Python", "Tableau", "Power BI", "Healthcare", "ETL", "dbt"],
        excludeKeywords: ["Java", "Senior Director", "VP", "C-Suite"],
        preferredCompanies: ["BCBS", "Optum", "Northwestern Medicine", "TechNova"],
        blacklistedCompanies: [],
      }),
    },
    {
      key: "scoringWeights",
      value: JSON.stringify({
        roleMatch: 35,
        locationMatch: 20,
        seniorityMatch: 20,
        keywordMatch: 15,
        sourceQuality: 10,
      }),
    },
    {
      key: "userPreferences",
      value: JSON.stringify({
        defaultView: "list",
        theme: "light",
        notificationsEnabled: true,
        autoScoreOnImport: true,
        showSalaryEstimates: true,
      }),
    },
  ]);
}
